name: Acquire activation file
on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 6000.0.28f1
      
      - name: Expose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.manualActivationFilePath }}